### ISSUE TITLE
Padding issue

### ISSUE THREAD

**Issue by rijkvanzanten** [rijkvanzanten/robat#27]
## Browser
Safari Version 10.1.1 (12603.2.4)

## Expected behavior
Messages align nicely with the bottom form

## Actual behavior
Messages render behind the form

<img width="938" alt="screen shot 2017-06-18 at 22 23 18" src="https://user-images.githubusercontent.com/9141017/27263931-c63db814-5474-11e7-8737-b16874c3a88f.png">

**Comment by dandevri** [comment]
On chrome *Version 59.0.3071.104 (Official Build) (64-bit)* this seems to be fine. Only a safari problem?

**Comment by rijkvanzanten** [comment]
That could very well be
