### ISSUE TITLE
Save messages in localStorage

### ISSUE THREAD

**Issue by rijkvanzanten** [rijkvanzanten/robat#31]
When the user refreshes the page, all previous messages are gone. It could be an easy, yet nice, enhancement to save the previous messages and show these to the user on subsequent visits.

**Comment by dandevri** [comment]
Let's use localForage for this.
* Client messages push to *same*  array
* Server messages push to *same* array
* Set the array in localforage
* Get the array client side
* Use the render message function

**Comment by rijkvanzanten** [comment]
```javascript
const messages = [
  {
    text: 'Hallo! Ik ben Robat, etc, etc',
    robat: true,
    id: 0
  },
  {
    text: 'Wat is de nieuwste CD van the White Stripes?'
    robat: false,
    id: 'C8901D'
  }
];
```

**Comment by dandevri** [comment]
The 'key' robat is unnecessary. The robat always has an 'id=0'.

**Comment by dandevri** [comment]
The `key` robat is unnecessary. The robat always has an `id=0`.

**Comment by rijkvanzanten** [comment]
sry bruh

**Comment by dandevri** [comment]
💔

**Comment by dandevri** [comment]
It kinda works but there are a few major issues:
* The first message is also saved which is rendered every time the user refreshes.
* localForage saves the messages before the class of the blue check marks is added. 

![screen shot 2017-06-21 at 14 10 43](https://user-images.githubusercontent.com/22084444/27383476-73c467a4-568b-11e7-9e74-7903967557e6.png)

**Comment by dandevri** [comment]
Fixed the duplicates in the bot but the blue checkmarks are still a problem.

**Comment by dandevri** [comment]
Basic localStorage functionality is added in #59.

**Comment by dandevri** [comment]
Still some enhancement to do. Would like to add a timestamp of some sort for previous conversations. (WhatsApp, Facebook style)

![screen shot 2017-06-21 at 17 11 09](https://user-images.githubusercontent.com/22084444/27391619-ad6beb94-56a4-11e7-9faa-f39154a5464d.png)

**Comment by dandevri** [comment]
Everytime the user makes a refresh or comes back to the page it renders a timestamp with the current time.

![image](https://user-images.githubusercontent.com/22084444/27435225-c7f268a0-575b-11e7-88f5-eaa400c75627.png)

But the timestamp isn't saved in localStorage.
![image](https://user-images.githubusercontent.com/22084444/27435254-ded0f46a-575b-11e7-8a28-72b2cd12817e.png)

And I can't use the same messageList array because those are only ~strings~ objects. @rijkvanzanten maybe you have an idea for a nice way to do this?

**IDEA**
I can store the timestamp as string in another array called `timestamp` and then set that in another localforage object?

**Comment by rijkvanzanten** [comment]
The `messageList` array contains Objects like:
```javascript
{
  value: 'Inhoud van Bericht'
  id: 'ADLK!08u'
}
```

You could add a timestamp key to each message, and group them by date / hour when rendering them to the dom on load.

Each time you add a message to the messageList, you add `message.timestamp = Date.now()`

**Comment by dandevri** [comment]
Understand the idea and that's smart but not sure how to implement it. 

Don't understand the last line:
> Each time you add a message to the messageList, you add message.timestamp = Date.now()

Date.now() are always numbers right?

**Comment by dandevri** [comment]
And, renderMessage always renders the messagelist forEach with the chat bubble styling. We don't want the timestamp to look like a chat bubble.

**Comment by rijkvanzanten** [comment]
Yeah you're right. It's a timestamp in ms.

You can save it as ms and then parse it back to a usable date like follows `const date = new Date(message.timestamp);`. You can then use this date object to get values like date, hour, year etc. See [the methods you can use on the date object](http://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)

**Comment by rijkvanzanten** [comment]
You probably want to group the messages in the messageList array by date and render a separate `<ul>` for each one of them.

**Comment by dandevri** [comment]
Oh staph it please. I have no idea how to do that. Let's look at this tomorrow.

**Comment by dandevri** [comment]
Timestamp is added with the code along refactor from #68
