### ISSUE TITLE
Create some more stories in wit.ai

### ISSUE THREAD

**Issue by dandevri** [rijkvanzanten/robat#45]
Based on the user testing there are some common (basic greeting stuff) that gets send to the user.

~What if someone sends their own name? Let's make a entity for that and store it in a variable.~
~`Hallo, ik ben Peter`~
~`Hallo, ik ben Emma`~

* What is robat currently doing? 
`Hoe gaat het`
`wat doe je`
`hoe is het`

* What gender is Robat 
`Ben je een man of een vrouw`
`Hoe ben je geboren`
`Door wie ben je gemaakt`

* Some more emotions for robat.
`Hoe voel je robat?`

**Comment by GiuliaM** [comment]
Created stories for each situation and added different interpretations of the questions to Wit.ai
