### ISSUE TITLE
Robat only answers after refresh

### ISSUE THREAD

**Issue by dandevri** [rijkvanzanten/robat#46]
It looks like the stop commando isn't properly working. 
* When the user sends the first message the robat response works fine
* After that the robat keeps giving the same response

The user has to refresh to get the answers to work. Only the first message that gets send works properly.

**Comment by dandevri** [comment]
When the user adds the website to homescreen in `safari` they can't refresh. On Chrome this functionality works.

**Comment by rijkvanzanten** [comment]
This is DEFCON 1

**Comment by rijkvanzanten** [comment]
(Should be) fixed by #52
