### ISSUE TITLE
Alter intro message

### ISSUE THREAD

**Issue by rijkvanzanten** [rijkvanzanten/robat#58]
It now says `Hallo ik ben Robat! Leuk dat je er bent :-)` but it should be a little more inviting. It wouldn't be a bad idea to add a `quickreply` story for this something like follows:

`Hallo! Ik ben Robat. Ik kan je helpen met al je vragen over de OBA. Wil je weten wat je me zoal kunt vragen?`
— `ja || nee`

**Comment by dandevri** [comment]
Nice idea to add something like a `/help` command! We can even enhance this by altering the intro message and sending something slightly different each time the users starts a new conversation.
* Store different intro messages in an array
* Pick one at random

Then we can create a story only with a specific keyword. Here are some examples:

* `Hi, mijn naam is Robat. Wil je weten wat je me zoal kunt vragen? Typ dan 'help'!`
* `Hallo, ik ben Robat. Je kan zien wat je me kan vragen door 'help' te typen.`

We then can create a story for the `help` keyword.

**Comment by dandevri** [comment]
Add this functionality in #64.

**Comment by dandevri** [comment]
Maybe we still change the text of the messages to  make them a bit more personal.

**Comment by GiuliaM** [comment]
Add help intent to wit ai with a personal message from Robat
