### ISSUE TITLE
Add working links in Robat

### ISSUE THREAD

**Issue by GiuliaM** [rijkvanzanten/robat#67]
You can paste a link in wit.ai, but it doesn't link to a website, it stays plain text. It would be better to be able to link it like this: [klik hier](https://www.oba.nl/oba/lidmaatschap-en-tarieven.html)

**Comment by dandevri** [comment]
Maybe a bit of a hack but it might work. Just came across this idea:

The message you receive from wit.ai is just a basic string right? Maybe you can add the `<a href="#"` HTML tags in the story in wit.ai and when the `renderMessage` function is called it might work? ¯\\\_(ツ)_/¯

**Comment by dandevri** [comment]
Just checked in wit.ai and you already tried it!
![screen shot 2017-06-23 at 22 48 45](https://user-images.githubusercontent.com/22084444/27499882-23923b44-5866-11e7-9810-cd6842a48222.png)

It has works. right? 
![screen shot 2017-06-23 at 22 49 17](https://user-images.githubusercontent.com/22084444/27499894-3e2debec-5866-11e7-93f8-9d42d3b0e176.png)

🎉
