### ISSUE TITLE
Enhance oba location story

### ISSUE THREAD

**Issue by dandevri** [rijkvanzanten/robat#74]
Nice that the bot gives the OBA location! Maybe we can even enhance it by making it a google maps link. The maps search link of `oba banne` is as follows:

`https://www.google.com/maps/place/Bezaanjachtplein+249`
`www.google.com/maps/place/`streetname`+`number`

**Comment by dandevri** [comment]
You can even put the whole string: `Bezaanjachtplein 249, 1034CR, AMSTERDAM` after the `maps/place/` link and it will give the right location in Google Maps.

**Comment by rijkvanzanten** [comment]
That seems like an easy fix, yet great enhancement 🙌🏻

**Comment by dandevri** [comment]
Add link to Google Maps. The anchor link now links to `https://www.google.nl/maps/place/{name}` where the {name} variable is the name of the OBA from the API.

![great-success-gif](https://user-images.githubusercontent.com/22084444/27536453-8622d2d6-5a6f-11e7-8d50-d48f39019ce0.gif)
