### ISSUE TITLE
Width of Robats chat bubbles is too wide

### ISSUE THREAD

**Issue by rijkvanzanten** [rijkvanzanten/robat#80]
<img width="821" alt="screen shot 2017-06-26 at 14 40 57" src="https://user-images.githubusercontent.com/9141017/27539628-84b5565e-5a7d-11e7-8218-c7b39220ddae.png">

Width should be `max-content` just like the user's messages but it's full width

**Comment by GiuliaM** [comment]
Solved at pr #82
