### ISSUE TITLE
Make sure the example questions actually work

### ISSUE THREAD

**Issue by rijkvanzanten** [rijkvanzanten/robat#92]
<img width="839" alt="screen shot 2017-06-27 at 23 52 17" src="https://user-images.githubusercontent.com/9141017/27611726-aa991ede-5b93-11e7-84e1-ffb7332accc7.png">

**Comment by GiuliaM** [comment]
"Wat kost een" is seen as a contact. So we changed it to "hoeveel kost een lidmaatschap"
